### ISSUE TITLE
Breaks if Skewness >= 1 as in BoE's latest forecast

### ISSUE THREAD

**Issue by brimoran** [quantgirluk/fanchart#1]
I love what you've done here.

I wanted to see if I could reproduce the latest BoE fanchart (August 2022) but I am encountering the attached error message.

I have played around a bit with the data to try to see what is causing the issue and I think it occurs when Skewness >= 1 as it is in the latest BoE projections for two periods
<img width="1010" alt="Screenshot 2022-08-12 at 17 25 16" src="https://user-images.githubusercontent.com/19614849/184403588-13003665-ba16-477d-84cc-2b30ac7a601b.png">

**Comment by quantgirluk** [comment]
Thanks for finding this issue. Investigation in progress.

**Comment by brimoran** [comment]
Great :)

**Comment by quantgirluk** [comment]
After investigating this issue, I have found that the package behaviour is consistent with the assumptions of the distribution forecasts as twopiece normals. That is, the skewness parameter should be in (-1, 1). So, the only change that I plan to make to the package is to raise an appropriate warning when parameters out of range are provided. I wrote a brief explanation about this on my [blog](https://quantgirl.blog/why-the-bank-of-england-parameters-for-cpi-inflation-are-out-of-range/). Thanks again for highlighting this to me.

**Comment by brimoran** [comment]
Interesting!  Great blog post.  Thanks for looking into this and for publishing your insight into what the out of range skewness implies.

**Comment by quantgirluk** [comment]
After some communication with BoE, they confirmed that what is published in their recent spreadsheet as Skewness is not the actual $\gamma$ parameter. Instead, they publish Skewness = difference between the mean and the median of the distribution. This quantity indeed can be outside the interval (-1, 1). So, what I did was to change my package twopiece (release 1.3.1) to accept this quantity and then calculate the parameter $\gamma$. This will in turn solve the issue with the fancharts. Besides, I updated fanchart (release 1.0.0) to require twopiece>=1.3.1. So, you can just update fanchart and the correct twopiece will be installed. 
Once again, thanks for highlighting this issue! It was very helpful.
